### ISSUE TITLE
Incorrent date and sender of messages

### ISSUE THREAD

**Issue by andreas-bulling** [sulami/feed2maildir#2] opened 2017-04-08 05:01 UTC
Hi,

feed2maildir is exactly what I was looking for. It works brilliantly except for two (minor but annoying problems)

1) mutt always shows "01 Jan 1970 01:00" as the date for the emails

2) the sender of messages is automatically composed into something that is difficult to read. It would be nice if this could instead be defined in the config line and/or whether the site name would be used instead

**Comment by rohieb** [comment] 2019-08-19 10:11
>     1. mutt always shows "01 Jan 1970 01:00" as the date for the emails

That happens for me too, but it seems to happen only on Atom feeds, not on RSS feeds. The reason is probably that RSS feeds use the same date format which is also used for e-mail ([RFC 2822](https://tools.ietf.org/html/rfc2822#section-3.3)), e.g.:

``` rss
<pubDate>Thu, 18 Jul 2019 19:15:00 -0700</pubDate>
```

but Atom uses the ISO 8601 date format:

``` atom
<updated>2019-08-18T13:33:37.798589+00:00</updated>
```

… which is not allowed in mail headers according to RFC 2822. So mail user agents use the default, `0`, which, when interpreted as Unix timestamp, results in `Thu, 01 Jan 1970 00:00:00 +0000`.

It seems kind of a bug to me that python-feedparser does not handle this correctly – I would expect a python `datetime` object here instead of a plain string.

>     2. the sender of messages is automatically composed into something that is difficult to read. It would be nice if this could instead be defined in the config line and/or whether the site name would be used instead

Here I have no idea…

**Comment by eldipa** [comment] 2020-06-27 03:45
I had the same issues. Some feeds have the wrong date format. As @rohieb said the problem is that Atom uses ISO 8601 date format instead of RFC 2822.

This can be fixed relatively easy (PR #7 )

The other issue is perhaps more subjective: the sender of the emails are built from the feed's title. Some titles are quite large making the sender a name too large and hard to read in an email reader like `mutt`

For example, the feed of the [engineering team of Github](https://githubengineering.com/) has the title `Engineering -- The GitHub Blog`.

I propose (PR #8 ) to use the feed name that the user set in the configuration file as the sender name and only for that. (This is important because the feed title is used as part of the database and we don't want to modify that so we can avoid any migration)

So if the user has the following configuration file, the emails will have `Github` as the name of the sender:

```
{                                                                                 
    "feeds": {                                                                                                                 
        "Github": "https://githubengineering.com/atom.xml"
    }                                                                                                                          
}
```

**Comment by sulami** [comment] 2020-06-28 19:53
I've merged both of your PRs and will release & push a new version to PyPI tomorrow.

**Comment by eldipa** [comment] 2020-12-14 13:37
@sulami I think that this issue can be closed.

**Closed as completed** 2020-12-15 10:16 UTC
